---
abstract: 'POE Client of the Nowa'
author:
  - 'woremacx <woremacx at cpan dot org>'
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Component-Client-Nowa
no_index:
  directory:
    - inc
    - t
requires:
  FindBin: 0
  Getopt::Long: 0
  POE: 0
  POE::Component::Server::IRC: 0
  POE::Component::TSTP: 0
  WebService::Nowa: 0
  YAML: 0
version: 0.01
